// Last updated: 2026-06-11
// To update: edit this file and push to GitHub

const EMPLOYEES = [
  { raw: "Abazov, Dimitri", display: "Dimitri Abazov", hireDate: "28/04/2025", manager: "Liliia Dergacheva", division: "Russian Editorial", dept: "Websites", title: "Writer" },
  { raw: "Abdullin, Artur", display: "Artur Abdullin", hireDate: "13/04/2021", manager: "Tatiana Chuprakova", division: "5-Minute Crafts YT", dept: "Video Film Content", title: "Remote Creator L2" },
  { raw: "Abdullina, Ilmira", display: "Ilmira Abdullina", hireDate: "04/04/2011", manager: "Zhanna Tsyruleva", division: "Distribution", dept: "Video Film Content", title: "SMM" },
  { raw: "Abdullina, Viktoriia", display: "Viktoriia Abdullina", hireDate: "01/06/2020", manager: "Svitlana Pavliukova", division: "Cool Tool WOW", dept: "Video Film Content", title: "Creative Producer" },
  { raw: "Abramova, Kamilla", display: "Kamilla Abramova", hireDate: "13/03/2019", manager: "Irina Sitnova", division: "123 GO!", dept: "Video Film Content", title: "Creative Producer" },
  { raw: "Agafonova, Evgeniia", display: "Evgeniia Agafonova", hireDate: "01/04/2024", manager: "Juta Beigarte", division: "One More", dept: "Video Film Content", title: "Remote Creator" },
  { raw: "Agapov, Ilia", display: "Ilia Agapov", hireDate: "18/11/2021", manager: "Natalija Janickina", division: "Distribution", dept: "Video Film Content", title: "Senior Lead Development Manager" },
  { raw: "Aidarkina, Anastasia", display: "Anastasia Aidarkina", hireDate: "06/10/2025", manager: "Tatiana Chuprakova", division: "LearnToon - Learn & Play", dept: "Video Film Content", title: "Remote Creator" },
  { raw: "Aidieva, Aizhan", display: "Aizhan Aidieva", hireDate: "05/02/2021", manager: "Tatiana Denisova", division: "Baby Zoo", dept: "Animated Content", title: "Associate Producer" },
  { raw: "Alekseeva, Rina", display: "Rina Alekseeva", hireDate: "02/05/2024", manager: "Tatiana Chuprakova", division: "LearnToon - Learn & Play", dept: "Video Film Content", title: "Remote Creator" },
  { raw: "Aleksejevska, Anastasija", display: "Anastasija Aleksejevska", hireDate: "26/04/2021", manager: "Juta Beigarte", division: "PuffPaw", dept: "Video Film Content", title: "Creative Supervisor" },
  { raw: "Andrejenkova, Jelena", display: "Jelena Andrejenkova", hireDate: "10/01/2022", manager: "Juta Beigarte", division: "One More", dept: "Video Film Content", title: "Remote Creator L3" },
  { raw: "Barkevics, Aleksandrs", display: "Aleksandrs Barkevics", hireDate: "30/04/2024", manager: "Juta Beigarte", division: "One More", dept: "Video Film Content", title: "Remote Creator L3" },
  { raw: "Bedics-Nemeth, Csilla", display: "Csilla Bedics-Nemeth", hireDate: "16/11/2022", manager: "Elizaveta Titova", division: "SKITS", dept: "Video Film Content", title: "Senior Lead Development Manager" },
  { raw: "Beigarte, Juta", display: "Juta Beigarte", hireDate: "02/06/2021", manager: "Svitlana Pavliukova", division: "SKITS", dept: "Video Film Content", title: "Creative Producer" },
  { raw: "Bernatovics, Arturs", display: "Arturs Bernatovics", hireDate: "01/07/2025", manager: "Juta Beigarte", division: "Jays Fast Science", dept: "Video Film Content", title: "Remote Creator L3" },
  { raw: "Bezrukov, Nikita", display: "Nikita Bezrukov", hireDate: "15/03/2018", manager: "Liudmila Podlesnova", division: "Bright Side YouTube", dept: "Animated Content", title: "Motion Designer L3" },
  { raw: "Boiarova, Anastasiia", display: "Anastasiia Boiarova", hireDate: "19/02/2019", manager: "Juta Beigarte", division: "One More", dept: "Video Film Content", title: "Creative Supervisor" },
  { raw: "Boikova, Anna", display: "Anna Boikova", hireDate: "21/05/2020", manager: "Liudmila Podlesnova", division: "Bright Side YouTube", dept: "Animated Content", title: "Script Supervisor" },
  { raw: "Bule, Polina", display: "Polina Bule", hireDate: "06/11/2023", manager: "Juta Beigarte", division: "One More", dept: "Video Film Content", title: "Remote Creator L3" },
  { raw: "Celmina, Evelina", display: "Evelina Celmina", hireDate: "01/12/2023", manager: "Juta Beigarte", division: "One More", dept: "Video Film Content", title: "Remote Creator L3" },
  { raw: "Chuprakova, Tatiana", display: "Tatiana Chuprakova", hireDate: "19/10/2020", manager: "Regina Garafieva", division: "5-Minute Crafts YT", dept: "Video Film Content", title: "Creative Producer" },
  { raw: "Emelianova, Daria", display: "Daria Emelianova", hireDate: "29/01/2025", manager: "Juta Beigarte", division: "La La Learn", dept: "Video Film Content", title: "Remote Creator" },
  { raw: "Ergunov, Dmitrii", display: "Dmitrii Ergunov", hireDate: "17/10/2017", manager: "Liudmila Podlesnova", division: "Bright Side YouTube", dept: "Animated Content", title: "Thumbnail Designer L3" },
  { raw: "Ermolaev, Vadim", display: "Vadim Ermolaev", hireDate: "09/04/2018", manager: "Liudmila Podlesnova", division: "Bright Side YouTube", dept: "Animated Content", title: "Lead Motion Designer" },
  { raw: "Evgraphov, Roman", display: "Roman Evgraphov", hireDate: "29/09/2021", manager: "Liudmila Podlesnova", division: "Bright Side YouTube", dept: "Animated Content", title: "Motion Designer L3" },
  { raw: "Fakhretdinova, Kamila", display: "Kamila Fakhretdinova", hireDate: "18/10/2021", manager: "Anastasiia Pukhova", division: "5-Minute Crafts YT", dept: "Video Film Content", title: "Remote Creator L2" },
  { raw: "Filimonov, Dmitry", display: "Dmitry Filimonov", hireDate: "29/10/2024", manager: "Tatiana Chuprakova", division: "5-Minute Craft YT", dept: "Video Film Content", title: "Remote Creator" },
  { raw: "Furman, Anastasiia", display: "Anastasiia Furman", hireDate: "01/04/2024", manager: "Irina Sitnova", division: "La La Life", dept: "Video Film Content", title: "SMM Product Owner" },
  { raw: "Gabdrakhmanova, Nailya", display: "Nailya Gabdrakhmanova", hireDate: "30/07/2021", manager: "Tatiana Chuprakova", division: "LearnToon - Learn & Play", dept: "Video Film Content", title: "Remote Creator" },
  { raw: "Garafieva, Regina", display: "Regina Garafieva", hireDate: "25/09/2017", manager: "Roman Zakharchenko", division: "", dept: "Video Film Content", title: "Senior Lead Producer" },
  { raw: "Gavrilova, Ilziia", display: "Ilziia Gavrilova", hireDate: "09/10/2024", manager: "Tatiana Chuprakova", division: "Distribution", dept: "Video Film Content", title: "Medior Content Manager" },
  { raw: "Ghilca, Denis", display: "Denis Ghilca", hireDate: "01/08/2018", manager: "Liudmila Podlesnova", division: "Bright Side YouTube", dept: "Animated Content", title: "Motion Designer L3" },
  { raw: "Griazeva, Regina", display: "Regina Griazeva", hireDate: "10/03/2020", manager: "Irina Sitnova", division: "123 GO! Projects", dept: "Video Film Content", title: "Creative Producer" },
  { raw: "Gubashiev, Anzor", display: "Anzor Gubashiev", hireDate: "26/12/2019", manager: "Liudmila Podlesnova", division: "AI Content Creation", dept: "IT", title: "AI Video Creator" },
  { raw: "Guimaraes Martins, Leticia", display: "Leticia Guimaraes Martins", hireDate: "06/05/2019", manager: "Liudmila Podlesnova", division: "Bright Side YouTube", dept: "Animated Content", title: "Scriptwriter L3" },
  { raw: "Gumerova, Albina", display: "Albina Gumerova", hireDate: "25/03/2025", manager: "Tatiana Chuprakova", division: "LearnToon - Learn & Play", dept: "Video Film Content", title: "Medior Content Manager" },
  { raw: "Irina Sitnova", display: "Irina Sitnova", hireDate: "", manager: "", division: "Distribution", dept: "Video Film Content", title: "Creative Producer" },
  { raw: "Konstantinov, Leonid", display: "Leonid Konstantinov", hireDate: "", manager: "", division: "5-Minute Crafts FB", dept: "Video Film Content", title: "Senior Content Manager" },
  { raw: "Mukhambetalieva, Iuliia", display: "Iuliia Mukhambetalieva", hireDate: "", manager: "", division: "5-Minute Crafts Girly", dept: "Video Film Content", title: "Senior Content Manager" },
  { raw: "Musin, Timur", display: "Timur Musin", hireDate: "", manager: "", division: "Distribution", dept: "Video Film Content", title: "Development Manager" },
  { raw: "Pavliukova, Svitlana", display: "Svitlana Pavliukova", hireDate: "", manager: "", division: "SKITS", dept: "Video Film Content", title: "Creative Producer" },
  { raw: "Podlesnova, Liudmila", display: "Liudmila Podlesnova", hireDate: "01/03/2020", manager: "Roman Zakharchenko", division: "Bright Side YouTube", dept: "Animated Content", title: "Creative Producer" },
  { raw: "Prohorenko, Valerija", display: "Valerija Prohorenko", hireDate: "", manager: "", division: "Distribution", dept: "Video Film Content", title: "Development Manager" },
  { raw: "Salcevics, Valerijs", display: "Valerijs Salcevics", hireDate: "01/04/2020", manager: "Louisa Ioannidou", division: "Studio Operations", dept: "General Management", title: "Senior Process Manager" },
  { raw: "Shigina, Irina", display: "Irina Shigina", hireDate: "", manager: "", division: "Distribution", dept: "Video Film Content", title: "Development Manager" },
  { raw: "Tarasova, Anna", display: "Anna Tarasova", hireDate: "", manager: "", division: "Facebook", dept: "Websites", title: "Senior Development Manager, Facebook" },
  { raw: "Tsyruleva, Zhanna", display: "Zhanna Tsyruleva", hireDate: "", manager: "", division: "Distribution", dept: "Video Film Content", title: "Senior Lead Development Manager" },
  { raw: "Zakharchenko, Roman", display: "Roman Zakharchenko", hireDate: "", manager: "", division: "Avocado Couple", dept: "Animated Content", title: "Lead Creative Producer" },
];

export default EMPLOYEES;
